const state={connected:false,jobsTimer:null};const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);
async function api(url,options={}){const r=await fetch(url,options);let body={};try{body=await r.json()}catch{}if(!r.ok)throw new Error(body.detail||`Erro ${r.status}`);return body}
function toast(message){const e=$('#toast');e.textContent=message;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),4000)}
function escapeHtml(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function show(view){$$('.view,.nav').forEach(e=>e.classList.remove('active'));$(`#view-${view}`).classList.add('active');$(`.nav[data-view="${view}"]`).classList.add('active')}
$$('.nav').forEach(b=>b.onclick=()=>show(b.dataset.view));

async function loadStats(){const s=await api('/api/stats');const values=[['Registros',s.records],['Vídeos únicos',s.media],['Analisados',s.analyzed_media],['Validados',s.validated_media],['Progresso',`${Math.round((s.analyzed_media||0)/Math.max(s.media||1,1)*100)}%`]];$('#metrics').innerHTML=values.map(v=>`<div class="metric"><span>${v[0]}</span><strong>${v[1]||0}</strong></div>`).join('')}
async function loadVideos(){const q=new URLSearchParams({search:$('#search').value,status:$('#status-filter').value,category:$('#category-filter').value});const d=await api('/api/videos?'+q);$('#result-count').textContent=`${d.total} registro(s)`;$('#videos').innerHTML=d.items.map(v=>`<tr><td>${escapeHtml(v.lesson_name)}</td><td>${escapeHtml(v.final_category||'—')}</td><td>${escapeHtml(v.summary||'—')}</td><td><span class="badge ${escapeHtml(v.status||'Pendente')}">${escapeHtml(v.status||'Pendente')}</span></td><td class="detail-cell" title="${escapeHtml(v.error_message||'')}">${escapeHtml(v.error_message||'—')}</td><td>${escapeHtml(v.jwplayer_id)}</td></tr>`).join('')}
let searchDelay;$('#search').oninput=()=>{clearTimeout(searchDelay);searchDelay=setTimeout(loadVideos,250)};$('#status-filter').onchange=loadVideos;$('#category-filter').onchange=loadVideos;

function applyConnection(s){state.connected=s.state==='connected';$('#mini-dot').classList.toggle('connected',state.connected);$('#mini-status').textContent=state.connected?'Biblioteca JW conectada':'JW Player desconectado';$('#status-icon').classList.toggle('connected',state.connected);$('#connection-title').textContent=state.connected?'Biblioteca conectada':s.state==='attention'?'Verificação necessária':'Não conectado';$('#connection-message').textContent=s.message;$('#continue-import').disabled=!state.connected;$('#upload').disabled=!state.connected;$('#import-lock').classList.toggle('unlocked',state.connected);$('#import-lock').textContent=state.connected?'Biblioteca conectada. Selecione a planilha para continuar.':'Conecte primeiro a biblioteca JW Player para liberar esta etapa.'}
async function loadConnection(verify=false){const s=await api('/api/jw/status'+(verify?'?verify=true':''));applyConnection(s);return s}
$('#login-form').onsubmit=async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;button.textContent='Conectando…';try{const s=await api('/api/jw/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:$('#jw-email').value,password:$('#jw-password').value})});$('#jw-password').value='';applyConnection(s);toast(s.message);if(s.state==='connected')show('import')}catch(err){toast(err.message)}finally{button.disabled=false;button.textContent='Abrir biblioteca e conectar'}};
$('#verify-session').onclick=async()=>{try{const s=await loadConnection(true);toast(s.message)}catch(e){toast(e.message)}};
$('#continue-import').onclick=()=>show('import');

const providerDefaults={Claude:'claude-sonnet-4-5',Ollama:'llava:7b'};
$('#provider').onchange=()=>{const provider=$('#provider').value;$('#api-key-label').style.display=provider==='Ollama'?'none':'block';$('#api-key-label').childNodes[0].nodeValue=`Chave ${provider}`;$('#api-key').placeholder='Cole a chave da API';$('#ai-model').value=providerDefaults[provider];if(provider==='Ollama')$('#frame-count').value='6'};
$('#analysis-mode').onchange=()=>{$('#whisper-label').style.display=$('#analysis-mode').value==='hybrid'?'block':'none'};
$('#spreadsheet').onchange=e=>{const file=e.target.files[0];if(file)e.target.parentElement.querySelector('strong').textContent=file.name};
$('#upload').onclick=async()=>{if(!state.connected)return toast('Conecte primeiro a biblioteca JW Player.');const file=$('#spreadsheet').files[0];if(!file)return toast('Selecione a planilha de vídeos.');const provider=$('#provider').value;if(provider!=='Ollama'&&!$('#api-key').value)return toast(`Informe a chave da ${provider} para iniciar a análise.`);const fd=new FormData();fd.append('file',file);fd.append('provider',provider);fd.append('api_key',$('#api-key').value);fd.append('model',$('#ai-model').value);fd.append('analysis_mode',$('#analysis-mode').value);fd.append('frame_count',$('#frame-count').value);fd.append('whisper_model',$('#whisper-model').value);const button=$('#upload');button.disabled=true;button.textContent='Validando e preparando fila…';try{const d=await api('/api/import-and-process',{method:'POST',body:fd});$('#api-key').value='';$('#import-result').innerHTML=`<div class="callout"><strong>Planilha incorporada</strong><span>${d.unique_media} vídeo(s) único(s); ${d.pending_media} pendente(s) enviado(s) para análise.</span></div>`;toast(`${d.jobs.length} vídeo(s) adicionados à fila`);show('processing');loadStats();loadVideos();loadJobs()}catch(e){toast(e.message)}finally{button.disabled=!state.connected;button.textContent='Enviar planilha e iniciar análise'}};

async function loadJobs(){const d=await api('/api/jobs');const active=d.items.filter(j=>j.state!=='paused').slice().reverse();const paused=d.items.filter(j=>j.state==='paused');let html=active.map(j=>`<div class="job"><header><strong>${escapeHtml(j.media_id)}</strong><span class="badge ${j.state==='error'?'Erro':j.state==='completed'?'Concluído':'Processando'}">${escapeHtml(j.state)}</span></header><small>${escapeHtml(j.message)}</small></div>`).join('');if(paused.length){const reason=paused.find(j=>j.message.includes('Claude:')||j.message.includes('Ollama:')||j.message.includes('sessão'))?.message||paused[0].message;html=`<div class="job batch-paused"><header><strong>Lote pausado</strong><span class="badge">${paused.length} item(ns)</span></header><small>${escapeHtml(reason)}</small><button class="button secondary" id="back-to-config">Voltar às configurações</button></div>`+html}$('#jobs').innerHTML=html||'<div class="empty">Nenhum trabalho iniciado.</div>';const back=$('#back-to-config');if(back)back.onclick=()=>show('import');clearTimeout(state.jobsTimer);if(d.items.some(j=>['queued','running'].includes(j.state)))state.jobsTimer=setTimeout(loadJobs,3000);else{loadStats();loadVideos()}}
$('#refresh').onclick=()=>Promise.all([loadStats(),loadVideos(),loadConnection(),loadJobs()]);
Promise.all([loadStats(),loadVideos(),loadConnection(),loadJobs()]).catch(e=>toast(e.message));
